services:
  postgres:
    image: postgres:17
    container_name: postgres-service
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - walt-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tablero-service
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "${PORT}:4000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - walt-network
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run build &&
        node ./dist/app.js
      "

networks:
  walt-network:
volumes:
  postgres_data:

