openapi: 3.0.1
info:
  title: prueba-tecnica-tablero
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Usa el esquema Login para autenticarte. Proporciona el token en el encabezado de autorización con el formato:
        ```
        Copia y Pega el token: <token>
        ```
paths:
  /api/v1/auth/login:
    post:
      summary: Login
      description: Login 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                  example: walter@gmail.com
                clave:
                  type: string
                  example: 123456
      responses:
        '200':
          description: Inicio exitoso
        '400':
          description: Credenciales invalidas

  /api/v1/auth/register:
    post:
      summary: Registro
      description: Registrar nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                  example: walter2@gmail.com
                clave:
                  type: string
                  example: 123456
      responses:
        '201':
          description: Usuario creado
        '400':
          description: Bad request

  /api/v1/tablero:
    get:
      summary: Listar tableros
      operationId: getTableros
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Listado de tableros
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: Tablero 1
                    descripcion:
                      type: string
                      example: Esta es la descripcion del tablero 1

    post:
      summary: Crear nuevo tablero
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: Tablero 1
                descripcion:
                  type: string
                  example: Esta es la descripcion del tablero 1
      responses:
        '201':
          description: Tablero created successfully

  /api/v1/tablero/{id}:
    patch:
      summary: Actualizar tablero
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: Tablero 1.1
      responses:
        '200':
          description: Tablero actualizado

    delete:
      summary: Eliminar tablero exitosamente
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tablero eliminado exitosamente

  /api/v1/tarea:
    get:
      summary: Listado de tareas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Listado de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    titulo:
                      type: string
                      example: Tarea 1
                    descripcion:
                      type: string
                      example: Esta es la descripcion del tablero 1

    post:
      summary: Crear nueva tarea
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: Tarea 1
                descripcion:
                  type: string
                  example: Esta es la descripcion del tablero 1
                estado_id:
                  type: integer
                  example: 1
                tablero_id:
                  type: integer
                  example: 1
      responses:
        '201':
          description: Tarea creada exitosamente

  /api/v1/tarea/{id}:
    patch:
      summary: Actualizar tarea
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                estado_id:
                  type: integer
                  example: 2
      responses:
        '200':
          description: Tarea actualizada exitosamente

    delete:
      summary: Delete tarea
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tarea eliminada exitosamente

  /api/v1/estado:
    get:
      summary: Obtener todos los estados
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Listar estados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: Estado 1

  /api/v1/reporte:
    get:
      summary: Obtener reporte de tareas por estado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Reporte de tareas por estado
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tablero_id:
                      type: integer
                      example: 1
                    estado:
                      type: array
                      items:
                        type: object
                        properties:
                          estado_id:
                            type: integer
                            example: 2
                          count:
                            type: integer
                            example: 1